name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: ExtraGalaxies/finsys-core/.github/workflows/npm-package-ci.yml@55120a74b073419c03c4427b7d7098bbfaec2442
    with:
      node-versions: '[20, 22, 24]'
