name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: ExtraGalaxies/finhero-devops/.github/workflows/npm-package-ci.yml@5519e02da278658131466d24540b2a4d15109a8d
    with:
      node-versions: '[20, 22, 24]'
