name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: ExtraGalaxies/finsys-core/.github/workflows/npm-package-ci.yml@0e5ea9ad63ca61cca3a85247ee9ebbc30e62cca1
    with:
      node-versions: '[24]'
