name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ExtraGalaxies/finsys-core/.github/workflows/npm-package-publish.yml@2a346a7bef0f3f153756fe0d64c7334a9d30069c
