name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ExtraGalaxies/finsys-core/.github/workflows/npm-package-publish.yml@5a73948b96e6b5f5544dbe4192382a8bd3f6b32e
