name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ExtraGalaxies/finsys-core/.github/workflows/npm-package-publish.yml@232a0318c134c7cac2b2b807aa59baecbae9e481
